### ISSUE TITLE
Looking for Sample Payload for pubsub transport which can be published from external systems

### ISSUE THREAD

**Issue by Vidya613** [rebus-org/Rebus.GoogleCloudPubSub#10]
we have created a solution with rebus saga handlers and gcp transport and and we have the subscriptions configured and in order this subscription to consume the payload published from other external systems what should be the format of the payoad if i have to publish from gcp pub sub. I guess i'm clear now.. Can anyone please help me with that..
For example i got this payload, i'm not sure if this is correct or not
{
"MessageType":"",
"MessageData":{
	"OrderId":12345,
	"BuyerId":67890,
	"TotalPrice":1000.0,
	"OrderItems":[{
		"ProductId":1,
		"Count":10,
		"Price":100.0
		}]
	},
"CorrelationId":"",
"ReplyToAddress":""
}

**Comment by mookid8000** [comment]
You can check out [TransportMessageExtensions.cs](https://github.com/rebus-org/Rebus.GoogleCloudPubSub/blob/master/Rebus.GoogleCloudPubSub/GoogleCloudPubSub/TransportMessageExtensions.cs) - it contains all the relevant mapping logic, so you can figure out the wire-level format to use when generating a pubsub message.
